version: '3'

tasks:
  build:
    cmds:
      - go build -v -i main.go

  gen:
    cmds:
      - solc --abi --bin ./contracts/CommitReveal.sol -o build --overwrite
      - >
        abigen --out ./contracts/commit_reveal.go
        --abi ./build/CommitReveal.abi
        --bin=./build/CommitReveal.bin
        --pkg contracts
        --type CommitReveal

  dev-mac:
    cmds:
      - brew tap ethereum/ethereum
      - brew install solidity
      - brew install ethereum
